### ISSUE TITLE
Session Problem

### ISSUE THREAD

**Issue by ArcanumArtis** [bathi-atra/lotgd_ds#1]
Heyho,

ich bekomme aktuell beim einloggen folgenden Fehler: Deine Sessionzeit ist abgelaufen. Bitte neu einloggen.

Kann dies eventuell an einer falschen PHP Einstellung liegen sprich session.gc_maxlifetime?

**Comment by bathi-atra** [comment]
Und falls nicht ob dieser commit hilft:

https://github.com/bathi-atra/lotgd_ds/commit/3caba21588e8d74ca8dac3bdf514cc4a7a192f0d

**Comment by ArcanumArtis** [comment]
Hey,

danke das zweite sprich die Änderung der common.php hat geholfen :) Und danke das du uns dieses Meisterwerk nochmals zur Verfügung stellst.

**Comment by bathi-atra** [comment]
Bitte :) freut mich, dass der Fix geholfen hat. 

Danke, dass war ein Fehler der schon 10+ Jahre in der README geschlummert hat und nie jemand bemerkt hat. 766 ist natürlich korrekt.
