### ISSUE TITLE
Kleiner Hinweis

### ISSUE THREAD

**Issue by ArcanumArtis** [bathi-atra/lotgd_ds#3]
Hey,

eventuell sollte in der README noch hinzugefügt werden das in der Datei: village.php - Zeile 140 $str_output .= get_title('`TS`Yt`ta`yd`&tzentrum Atra`yh`to`Yr`Ts').' der Name der Stadt manuell angepasst werden muss. Zwar lässt sich das auch mit `.getsetting('townname','Atrahor').'s ` umgehen ist aber dann nicht mehr so schön :).

**Comment by bathi-atra** [comment]
Danke, aber denke, dass ich nicht nötig. Ich kann die Stelle aber im Code entfernen. :)
