### ISSUE TITLE
Stalltier-Editor defekt? 

### ISSUE THREAD

**Issue by DerDiox** [bathi-atra/lotgd_ds#4]
Versucht man in der Grotte - Stalltiereditor ein Tier zu bearbeiten. 
Hier z.B. dem Schlaufuchs mehr Waldrunden zu geben dann tritt folgende Fehlermeldung auf

[Fri May 28 17:41:35.709306 2021] [proxy_fcgi:error] [pid 23067:tid 139880658454272] [client xxxxxxxxxxxx] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/vhosts/xxxxxxxx.stratoserver.net/httpdocs/su_mounts.php:116\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/xxxxxxxx.stratoserver.net/httpdocs/su_mounts.php on line 116', referer: https://xxxxxxx.stratoserver.net/su_mounts.php?op=edit&id=73

Der Browser kann nichts anzeigen aber man kann zurück.

**Comment by bathi-atra** [comment]
Danke behoben:

https://github.com/bathi-atra/lotgd_ds/commit/7c89d9c8e817f43eb9ddb132248e3ad582e34d35
