### ISSUE TITLE
Gästebuch / Biografie

### ISSUE THREAD

**Issue by DerDiox** [bathi-atra/lotgd_ds#7]
Ich weiß nicht ob das Problem bei allen besteht aber bei uns lassen sich Gästebuch Einträge nicht speichern. 
Einer hat funktioniert. Alle weiteren Kombinationen scheitern mit der folgenden Fehlermeldung.

https://imgur.com/3WYNrw6

**Comment by bathi-atra** [comment]
Da scheint im im install.sql zu fehlen, dass das Feld id PRIMARY KEY und AUTO_INCREMENT braucht. :)

**Comment by bathi-atra** [comment]
Siehe https://github.com/bathi-atra/lotgd_ds/commit/ddd748ffabdb6ed1a61098d989e285366555b853
